import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import sync


class ModelSyncTests(unittest.TestCase):
  def test_rejects_invalid_python_property_names(self):
    definition = {
      "type": "object",
      "properties": {
        "bad-name": {"type": "string"},
      },
    }

    with self.assertRaises(ValueError):
      sync.generate_model_code("BadModel", definition, {})

  def test_rejects_unsafe_docstring_text(self):
    definition = {
      "type": "object",
      "description": 'unsafe """ docstring',
      "properties": {
        "name": {"type": "string"},
      },
    }

    with self.assertRaises(ValueError):
      sync.generate_model_code("BadModel", definition, {})

  def test_validate_sync_detects_generated_content_drift(self):
    definitions = {
      "Foo": {
        "type": "object",
        "required": ["name"],
        "properties": {
          "name": {"type": "string"},
        },
      },
    }

    with tempfile.TemporaryDirectory() as tmp:
      output_dir = Path(tmp)
      (output_dir / "context.py").write_text(
        '"""GENERATED BY METIS - DO NOT EDIT DIRECTLY"""\n'
        "from pydantic import BaseModel\n\n"
        "class Foo(BaseModel):\n"
        "  pass\n",
        encoding="utf-8",
      )
      (output_dir / "__init__.py").write_text(
        '"""Generated models from Metis sync."""\n'
        "from .context import Foo\n\n"
        "__all__ = ['Foo']\n",
        encoding="utf-8",
      )

      projects = {
        "demo": {
          "path": str(output_dir),
          "models": ["Foo"],
        },
      }
      with patch.object(sync, "PROJECTS", projects):
        self.assertFalse(sync.validate_sync(definitions))


if __name__ == "__main__":
  unittest.main()
